name: cosmos_ui_components
description: Cosmos UI componen ts
version: 0.0.1
author: andrzejchm
homepage: tendermint.com
publish_to: 'none' # TODO publish it when ready

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cosmos_utils:
    git:
      url: https://github.com/tendermint/flutter.git
      path: packages/cosmos_utils
      ref: main


dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

flutter: